### ISSUE TITLE
指定output路径报错

### ISSUE THREAD

**Issue by qingzhoufeihu** [vicwang163/react-to-vue#10]
rtv --output E:\crm-vue\file\a.vue  file E:\CRM\trunk\src\containers\framework\containers\toptab\index.js
![image](https://user-images.githubusercontent.com/26052806/37693438-a3f1b47c-2cfa-11e8-8d25-e019e795c672.png)

**Comment by vicwang163** [comment]
@qingzhoufeihu 我试了是都是没有问题的，如果在windows下面：`rtv --output C:\Users\vic.wang\Documents\a.vue C:\Users\vic.wang\Documents\react.js`
我看了你的出错，是因为文件路径有问题，为什么会有`file E`这样的路径
