### ISSUE TITLE
老哥 有没有考虑把vue 转 react？

### ISSUE THREAD

**Issue by Yunnathai** [vicwang163/react-to-vue#11]
Please copy your code of React Component into the following block
 
 ``` jsx
 // your code
 
 ```

**Comment by anchengjian** [comment]
😂再这么转下去都转成一个环了

**Comment by anchengjian** [comment]
再这么转下去都转成一个环了

**Comment by Yunnathai** [comment]
楼上是mpvue团队的大佬吗。
没 只是刚好有vue 需要转react的项目需求。为了转RN

**Comment by vicwang163** [comment]
@jamninetyfive vue的语法糖太多，有些不一定能转或者有些比较麻烦，再说现在react项目比较多，你这样的需求还是非常少的，你就先自己写吧
