### ISSUE TITLE
如何区分this.props.a还是this.state.a

### ISSUE THREAD

**Issue by profitfrl** [vicwang163/react-to-vue#17]
Please copy your code of React Component into the following block
 
 ``` jsx
 // your code
 
 ```

**Comment by profitfrl** [comment]
如何区分this.props.a还是this.state.a，转换后都是this.a。
如果this.props.a跟this.state.a 同时存在会有问题

**Comment by vicwang163** [comment]
@profitfrl 是的，vue都是用this的，所以如果有重复，我会有修正
