### ISSUE TITLE
Is it possible that transform React JSX to Vue template?

### ISSUE THREAD

**Issue by yuche** [vicwang163/react-to-vue#6]
Transform following code: 

```jsx
return () {
  return this.props.items.map((item, index) => {
    return  <li>{`${index} - ${item.message}`}</li>
 })
}
```

to:

``` jsx
<li v-for="(item, index) in items">
 {{ index }} - {{ item.message }}
</li>
 ```

It would be nice to have this feature.

**Comment by vicwang163** [comment]
@yuche transformation is limited, as render function may contain some codes except for return statement which will be difficult to be transformed. vue template is simple and fast to build easy view, for complex view, vue also recommend to use jsx
BTW, vue template is easily transformed to jsx
